main:
  - name: Главная
    url: /
    weight: 1
  - name: Статьи
    url: /posts/
    weight: 2
  - name: Фото
    url: /фото/
    weight: 3
  - name: Обо мне
    url: /добро-пожаловать-в-мой-блог/
    weight: 4
  - name: Материалы
    url: /материалы/
    weight: 5
  - name: Рекомендации
    url: /рекомендации/
    weight: 6
