main:
  - name: nav.home
    pageRef: /
    weight: 10
    params:
      icon: home
  - name: nav.posts
    pageRef: /posts
    weight: 20
    params:
      icon: posts
  - name: nav.now
    pageRef: /now
    weight: 25
    params:
      icon: book-open
  - name: nav.categories
    pageRef: /categories
    weight: 30
    params:
      icon: categories
  - name: nav.tags
    pageRef: /tags
    weight: 40
    params:
      icon: tags
  - name: nav.contact
    url: mailto:xaku68@gmail.com
    weight: 60
    params:
      icon: contact

# footer menu
footer:
  - name: nav.contact
    url: mailto:xaku68@gmail.com
    weight: 20
    params:
      icon: contact
  - name: footer.rss_feed
    url: /index.xml
    weight: 30
    params:
      icon: rss

# footer social link
social:
  - name: ВКонтакте
    url: https://vk.com/xakuorg
    weight: 10
    params:
      icon: vk
  - name: Телеграм
    url: https://t.me/SKWTMB
    weight: 20
    params:
      icon: telegram
  - name: Email
    url: mailto:xaku68@gmail.com
    weight: 30
    params:
      icon: email
  - name: НИУ ВШЭ
    url: https://www.hse.ru/staff/STARODUBOV/
    weight: 40
    params:
      icon: library

